version: '3.7'

services:
  fz-nginx:
    container_name: fz-nginx
    build:
      context: .docker/nginx
      args:
        uid: ${HOST_UID}
    ports:
      - ${HOST_PORT}:8000
    volumes:
      - .:/var/www

  fz-php:
    container_name: fz-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        xdebug: ${XDEBUG_STATUS}
        uid: ${HOST_UID}
        github_api_token: ${GITHUB_API_TOKEN}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - .:/var/www

  fz-composer:
    container_name: fz-composer
    build:
      context: .
      dockerfile: .docker/composer/Dockerfile
      args:
        uid: ${HOST_UID}
        github_api_token: ${GITHUB_API_TOKEN}
    volumes:
      - ./:/var/www
    command: composer install

  fz-mysql:
    image: mysql:5.7
    container_name: fz-mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - fz-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

  fz-redis:
    container_name: fz-redis
    image: redis:5.0-alpine
    ports:
      - ${REDIS_HOST_PORT}:6379

networks:
  default:
      name: fz-network

volumes:
  fz-db:
  fz-rds:
